### ISSUE TITLE
Generate historic measurement and weather data in time-series store

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#674]
### Tasks
- [x] Review weather file shared by Jeff to make sure we have all the fields that GridLAB-D needs. (Andy)
- [x] Put 1 year data in proven (Eric/Todd)
- [x] Create API to store and retrieve historic data (Poorva)
- [ ] Update Viz to make historic data request (Bibi)
- [x] Get the weather data need from NREL. (Tom)
- [ ] Needs to run simulation without application (Tara)
- [x] Should be able to run with houses  (Andy)
- [ ] Should be able to run with sensor service (Tom)

### Description of Issue
User need to run a simulation with an application that requires historic data for measurements and weather. For Example: VVO requires 2 weeks of historic data before running a simulation. 

### Process Details
1. User would a send a request to run a simulation with historic data requirements. Historic data request would be similar to simulation request with following difference: no application, different simulation start time and a time range. 
2. This request would start 2 simulations one after another. First simulation would generate data and store in time series store. Second simulation will start once first simulation is completed and data is available. 
3. Result from second simulation would be visible on viz (For now).

### Data needed :
1. Measurements from simulation output in time series store
2. Weather data
        -  For now: Data from weather file shared by Jeff. 
        - Later: May be from NSRDB website or others (csv files, can be huge) should have time context for the given simulation. What weather the simulation uses - can work with that. 

### Affected Version
Sep 2018

**Comment by blthayer** [comment]
@poorva1209 - finally getting around to reviewing this, sorry for the delay.

At first glance, the descriptions looks good. The only comment I would add: 

As it stands, it reads "Historic data request would be similar to simulation request with following difference: no application,..."

However, I can see the use in having application(s) run for the historic simulation, since applications could (or will likely) make an impact on simulation output. It would need to be application(s) which don't need historic data, of course. This is absolutely not needed for the implementation needed for September, but long term it would be worthwhile.

**Comment by ericstephan** [comment]
After a couple of iterations I've got a repository that is ready to be dockerized, I believe.

https://github.com/GRIDAPPSD/gridappsd-data

In the timeseries/weather/solar-forecasting directory is a script based on Jeff's original script that does not rely on additional python library installations (influxdb, dataframe).  It instead relies on the client influx command line tool to import the data. 

The basic steps are outlined in the readme file:
1) Make sure Influx is running

2) build bulkload file: python3 build_bulk_load_file.py
3) At command prompt: influx -import -path=ghi_dhi_bulkload.txt -precision ms



Jeff - Some additions Tom, Tara, and Poorva discussed was to break out the month, day, and year as separate integer fields that can be used by the weather API for subselecting the data based on the month and month day while ignoring the year.



Eric
